name: deploy on release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Load repository
      uses: actions/checkout@v4

    - name: Prepare site content
      run: |
        VER='${{ github.event.release.tag_name }}'
        mkdir -p output/"$VER"
        cp -r index.html ru en output/"$VER"/

        
    - name: Upload to Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        keep_files: true
