name: deploy on release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Load repository
      uses: actions/checkout@v4

    - name: Prepare site content
      run: |
        mkdir output
        mkdir output/${{ github.event.release.tag_name }}
        cp -r *.html ru/ en/ output/${{ github.event.release.tag_name }}/
        find output/${{ github.event.release.tag_name }} -name "*.html" -exec sed -i "s|/lab4/|/lab4/${{ github.event.release.tag_name }}/|g" {} \;

    - name: Upload to Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        keep_files: true
